icons = {
    "Comfyroll/Upscale": "🧩 Comfyroll Studio/✨ Essential/🔍 Upscale",
    "Comfyroll/Model Merge": "🧩 Comfyroll Studio/✨ Essential/⛏️ Model Merge",
    "Comfyroll/Utils/Logic": "🧩 Comfyroll Studio/🛠️ Utils/🔀 Logic",
    "Comfyroll/Utils/Conditional": "🧩 Comfyroll Studio/🛠️ Utils/🔀 Conditional", 
    "Comfyroll/Utils/Process": "🧩 Comfyroll Studio/🛠️ Utils/🔂 Process",
    "Comfyroll/Utils/Index": "🧩 Comfyroll Studio/🛠️ Utils/🔢 Index",
    "Comfyroll/Utils/Conversion": "🧩 Comfyroll Studio/🛠️ Utils/🔧 Conversion",
    "Comfyroll/Utils/Random": "🧩 Comfyroll Studio/🛠️ Utils/🎲 Random",
    "Comfyroll/Utils/Text": "🧩 Comfyroll Studio/🛠️ Utils/🔤 Text",    
    "Comfyroll/Utils/Other": "🧩 Comfyroll Studio/🛠️ Utils/⚙️ Other",
    "Comfyroll/LoRA": "🧩 Comfyroll Studio/✨ Essential/💊 LoRA",
    "Comfyroll/ControlNet": "🧩 Comfyroll Studio/✨ Essential/🕹️ ControlNet",
    "Comfyroll/XY Grid": "🧩 Comfyroll Studio/✨ Essential/📉 XY Grid",
    "Comfyroll/SDXL": "🧩 Comfyroll Studio/✨ Essential/🌟 SDXL",
    "Comfyroll/List": "🧩 Comfyroll Studio/✨ Essential/📜 List",
    "Comfyroll/List/IO": "🧩 Comfyroll Studio/✨ Essential/📜 List/⌨️ IO",    
    "Comfyroll/List/Utils": "🧩 Comfyroll Studio/✨ Essential/📜 List/🛠️ Utils",      
    "Comfyroll/Aspect Ratio": "🧩 Comfyroll Studio/✨ Essential/🔳 Aspect Ratio",
    "Comfyroll/Workflow": "🧩 Comfyroll Studio/✨ Essential/Workflow",     
    "Comfyroll/Essential/Core": "🧩 Comfyroll Studio/✨ Essential/📦 Core",
    "Comfyroll/Essential/Legacy": "🧩 Comfyroll Studio/✨ Essential/💀 Legacy",

}
